import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Footer } from "@/components/Footer";
import { PopupWidget }  from "@/components/PopupWidget";
import Navbar from "@/components/ui/header-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="bg-white min-h-screen w-full">
      <body className={inter.className + " bg-white text-red-700 min-h-screen w-full"}>
        <Navbar />
        <div className="w-full max-w-screen-2xl mx-auto px-2 sm:px-4 md:px-8 lg:px-16 xl:px-32">
          {children}
        </div>
        <Footer />
        <PopupWidget />
      </body>
    </html>
  );
}
